### ISSUE TITLE
Unable to run example

### ISSUE THREAD

**Issue by VineetTambe** [etaoxing/sgm-sorb#2]
Hey,
I am trying to run the example but am unable to do so because the standard packages don't work and have breaking changes as their versions have been upgraded.
Could you tell me:
1. What were the package dependencies and their versions used?
2. What is the latest research in this field or extending sgm-sorb futher (I am still exploring the space)

**Comment by etaoxing** [comment]
1. Seems like it runs with a lower gym version and torch==2.0, I just updated `setup.py`.
2. I can't help you conduct literature review, maybe start [here](https://scholar.google.com/scholar?cites=14782939310889640294).
